horeca_middleware_client:
    provider_api_class: App\Service\ProviderApi
    enable_request_exception_logging: '%env(resolve:HORECA_ENABLE_REQUEST_EXCEPTION_LOGGING)%'
    order_notification_messenger_transport: 'hmc_order_notification'
